plugins {
    id 'groovy'
    id 'java'
}

group 'org.iskyc.lulech'
version '1.0-SNAPSHOT'

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    localGroovy()
    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-web', version: 'latest.integration'
    implementation group: 'org.springframework.data', name: 'spring-data-elasticsearch', version: 'latest.integration'
    implementation group: 'io.projectreactor', name: 'reactor-core', version: 'latest.integration'
}
